# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 18:47
from __future__ import unicode_literals

import apps.project.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('academic_degree', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], default='BACHELOR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(default='/static/images/default_project_image.jpg', upload_to=apps.project.models.project_directory_path)),
                ('project_image_cropped', models.ImageField(default='/static/images/default_project_image.jpg', upload_to=apps.project.models.project_directory_path)),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('semester', models.CharField(choices=[('SS', 'Summer semester'), ('WS', 'Winter semester')], default='SS', max_length=2)),
                ('year_from', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016)),
                ('year_to', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016)),
                ('views', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('approval_state', models.CharField(choices=[('EDITABLE', 'For users to edit'), ('FOR_REVIEW', 'For supervisors to review'), ('FOR_REVISION', 'For users to improve'), ('APPROVED', 'Publicly viewable')], default='EDITABLE', max_length=20)),
                ('search_string', models.TextField(default='-', max_length=5000)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.DegreeProgram')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SLIDESHOW', 'Slideshow'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='TEXT', max_length=10)),
                ('content', models.TextField(default='{"subheading": "", "text": ""}', max_length=2000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_username', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemberResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectMember')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(default='', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Social')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User', validators=[apps.project.models.can_be_supversivor])),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('degree_programs', models.ManyToManyField(to='project.DegreeProgram')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Tag'),
        ),
        migrations.AddField(
            model_name='projectmemberresponsibility',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Tag'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='responsibilities',
            field=models.ManyToManyField(related_name='member_responsibility', through='project.ProjectMemberResponsibility', to='project.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='project_member', through='project.ProjectMember', to='user.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='socials',
            field=models.ManyToManyField(related_name='project_social', through='project.ProjectSocial', to='user.Social'),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Subject'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(related_name='project_supervisor', through='project.ProjectSupervisor', to='user.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='project_tag', through='project.ProjectTag', to='project.Tag'),
        ),
    ]
