# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170213_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approval_state',
            field=models.CharField(choices=[('EDITABLE', 'Bearbeitbar durch Nutzer'), ('FOR_REVIEW', 'Abnahme durch Verantwortlichen'), ('FOR_REVISION', 'Korrekturphase'), ('APPROVED', 'Freigegeben - öffentlich einsehbar')], default='EDITABLE', max_length=20),
        ),
    ]
