# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='new'),
        ),
    ]
