# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170307_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadaudio',
            old_name='clip',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image',
            new_name='file',
        ),
    ]
